USE `HotelChainDB`;

alter table HOTELFEATURES
  add CONSTRAINT `fk_HOTEL_FEATURES_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table HOTELPHONENUMBER
  add CONSTRAINT `fk_HOTEL_PHONE_NUMBER_HOTEL`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table EMPLOYEE  
 add CONSTRAINT `fk_EMPLOYEE_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table GUESTPHONENUMBER 
  add CONSTRAINT `fk_GUEST_PHONE_NUMBER_GUEST1`
    FOREIGN KEY (`guestID`)
    REFERENCES `HotelChainDB`.`GUEST` (`guestID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ROOMTYPE
  add CONSTRAINT `fk_ROOMTYPE_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ROOM
  add CONSTRAINT `fk_ROOM_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ROOM
  add CONSTRAINT `fk_ROOM_ROOMTYPE1`
    FOREIGN KEY (`RTname`)
    REFERENCES `HotelChainDB`.`ROOMTYPE` (`RTname`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION
  add CONSTRAINT `fk_RESERVATION_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION
  add CONSTRAINT `fk_RESERVATION_GUEST1`
    FOREIGN KEY (`guestID`)
    REFERENCES `HotelChainDB`.`GUEST` (`guestID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table USER
  add CONSTRAINT `fk_USER_ROLES1`
    FOREIGN KEY (`roleID`)
    REFERENCES `HotelChainDB`.`ROLES` (`roleID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ADMIN
  add CONSTRAINT `fk_ADMIN_ROLES1`
    FOREIGN KEY (`roleID`)
    REFERENCES `HotelChainDB`.`ROLES` (`roleID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table DESKCLERK
  add CONSTRAINT `fk_DESK-CLERK_ROLES1`
    FOREIGN KEY (`roleID`)
    REFERENCES `HotelChainDB`.`ROLES` (`roleID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION_HAS_ROOM
  add CONSTRAINT `fk_RESERVATION_has_ROOM1_RESERVATION2`
    FOREIGN KEY (`reservationID` , `hotelID` , `guestID`)
    REFERENCES `HotelChainDB`.`RESERVATION` (`reservationID` , `hotelID` , `guestID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION_HAS_ROOM
  add CONSTRAINT `fk_RESERVATION_has_ROOM1_ROOM2`
    FOREIGN KEY (`roomNumber`)
    REFERENCES `HotelChainDB`.`ROOM` (`roomNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table SEASON_HAS_HOTEL
  add CONSTRAINT `fk_SEASON_has_HOTEL_SEASON1`
    FOREIGN KEY (`seasonName`)
    REFERENCES `HotelChainDB`.`SEASON` (`seasonName`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table SEASON_HAS_HOTEL
  add CONSTRAINT `fk_SEASON_has_HOTEL_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION_HAS_SERVICES
  add CONSTRAINT `fk_RESERVATION_has_SERVICES_RESERVATION1`
    FOREIGN KEY (`reservationID` , `hotelID` , `guestID`)
    REFERENCES `HotelChainDB`.`RESERVATION` (`reservationID` , `hotelID` , `guestID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION_HAS_SERVICES
  add CONSTRAINT `fk_RESERVATION_has_SERVICES_SERVICES1`
    FOREIGN KEY (`serviceID`)
    REFERENCES `HotelChainDB`.`SERVICES` (`serviceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table RESERVATION_BILL 
  add CONSTRAINT `fk_RESERVATION_BILL_RESERVATION1`
    FOREIGN KEY (`reservationID` , `hotelID` , `guestID`)
    REFERENCES `HotelChainDB`.`RESERVATION` (`reservationID` , `hotelID` , `guestID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ROOMTYPEWEEKDAYPRICE
  add CONSTRAINT `fk_ROOMTYPEWEEKDAYPRICE_ROOMTYPE1`
    FOREIGN KEY (`RTname` , `hotelID`)
    REFERENCES `HotelChainDB`.`ROOMTYPE` (`RTname` , `hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table ROOMTYPEFEATURES
  add   CONSTRAINT `fk_ROOMTYPEFEATURES_ROOMTYPE1`
    FOREIGN KEY (`RTname` , `hotelID`)
    REFERENCES `HotelChainDB`.`ROOMTYPE` (`RTname` , `hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table HOTEL_PROVIDES_SERVICES
  add CONSTRAINT `fk_SERVICES_has_HOTEL_HOTEL1`
    FOREIGN KEY (`hotelID`)
    REFERENCES `HotelChainDB`.`HOTEL` (`hotelID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table HOTEL_PROVIDES_SERVICES
  add CONSTRAINT `fk_SERVICES_has_HOTEL_SERVICES1`
    FOREIGN KEY (`serviceID`)
    REFERENCES `HotelChainDB`.`SERVICES` (`serviceID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;